import { RootLayout } from '../components/pages/Layout'

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Template',
  description: 'Generated by create next app'
}

export default RootLayout
